// <auto-generated />
using System;
using BackEnd_S5_L5.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd_S5_L5.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251206060133_modify verbale")]
    partial class modifyverbale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd_S5_L5.Models.Entities.Anagrafica", b =>
                {
                    b.Property<Guid>("IdAnagrafica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cap")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAnagrafica");

                    b.ToTable("Anagrafiche");
                });

            modelBuilder.Entity("BackEnd_S5_L5.Models.Entities.TipoViolazione", b =>
                {
                    b.Property<Guid>("IdViolazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdViolazione");

                    b.ToTable("TipoViolazioni");
                });

            modelBuilder.Entity("BackEnd_S5_L5.Models.Entities.Verbale", b =>
                {
                    b.Property<Guid>("IdVerbale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataTrascrizioneVerbale")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataViolazione")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecurtamentoPunti")
                        .HasColumnType("int");

                    b.Property<Guid>("IdAnagraficaFk")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdViolazioneFk")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IndirizzoViolazione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NominativoAgente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdVerbale");

                    b.HasIndex("IdAnagraficaFk");

                    b.HasIndex("IdViolazioneFk");

                    b.ToTable("Verbali");
                });

            modelBuilder.Entity("BackEnd_S5_L5.Models.Entities.Verbale", b =>
                {
                    b.HasOne("BackEnd_S5_L5.Models.Entities.Anagrafica", "Anagrafica")
                        .WithMany("Verbali")
                        .HasForeignKey("IdAnagraficaFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_S5_L5.Models.Entities.TipoViolazione", "TipoViolazione")
                        .WithMany("Verbali")
                        .HasForeignKey("IdViolazioneFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anagrafica");

                    b.Navigation("TipoViolazione");
                });

            modelBuilder.Entity("BackEnd_S5_L5.Models.Entities.Anagrafica", b =>
                {
                    b.Navigation("Verbali");
                });

            modelBuilder.Entity("BackEnd_S5_L5.Models.Entities.TipoViolazione", b =>
                {
                    b.Navigation("Verbali");
                });
#pragma warning restore 612, 618
        }
    }
}
